dnsmasq:
  image: rsoares/dnsmasq
  ports:
   - "172.17.42.1:53:53/udp"
  volumes:
   - /etc/timezone:/etc/timezone:ro
   - /tmp/share:/tmp/share
  privileged: true
  hostname: dnsmasq
jonpostgres:
  image: rsoares/jon-postgres:9.4
  environment:
   - POSTGRESQL_USER=rhqadmin
   - POSTGRESQL_PASSWORD=rhqadmin
   - POSTGRESQL_DATABASE=rhq
   - POSTGRESQL_ADMIN_PASSWORD=postgres@123
   - POSTGRESQL_SHARED_BUFFERS=80
  volumes_from:
   - dnsmasq
  volumes:
   - /etc/timezone:/etc/timezone:ro
   - /tmp/share:/tmp/share
  privileged: true
  hostname: jon-postgres
  links:
   - dnsmasq
  dns:
   - 172.17.42.1
jonserver:
  image: rsoares/jon-server
  ports:
   - "7080:7080"
  volumes_from:
   - dnsmasq
  volumes:
   - /etc/timezone:/etc/timezone:ro
   - /tmp/share:/tmp/share
  privileged: true
  hostname: jon-server
  links:
   - jonpostgres
  dns:
   - 172.17.42.1
ewshttpd:
  image: rsoares/ews
  ports:
   - "80:80"
   - "6666:6666"
  volumes_from:
   - dnsmasq
  volumes:
   - /etc/timezone:/etc/timezone:ro
   - /tmp/share:/tmp/share
  privileged: true
  hostname: apache
  dns:
   - 172.17.42.1
eapmaster:
  image: rsoares/eap
  ports:
   - "9990:9990"
   - "9999:9999"
  command: domain --host-config=host-master.xml --master-address=localhost
  volumes_from:
   - dnsmasq
  volumes:
   - /etc/timezone:/etc/timezone:ro
   - /tmp/share:/tmp/share
  privileged: true
  hostname: master
  links:
   - dnsmasq
  dns:
   - 172.17.42.1
eapslave1:
  image: rsoares/eap
  command: domain --host-config=host-slave.xml --master-address=master
  volumes_from:
   - dnsmasq
  volumes:
   - /etc/timezone:/etc/timezone:ro
   - /tmp/share:/tmp/share
  privileged: true
  hostname: eap-slave1
  links:
   - dnsmasq
  dns:
   - 172.17.42.1
eapslave2:
  image: rsoares/eap
  command: domain --host-config=host-slave.xml --master-address=master
  volumes_from:
   - dnsmasq
  volumes:
   - /etc/timezone:/etc/timezone:ro
   - /tmp/share:/tmp/share
  privileged: true
  hostname: eap-slave2
  links:
   - dnsmasq
  dns:
   - 172.17.42.1
